[theme]
# Color de acento (checks, botones activos, etc.)
primaryColor = "#000000" 

# Fondo principal de la aplicación (Tu rojo corporativo)
backgroundColor = "#e34c48"

# Fondo de widgets (selectbox, inputs) y del Sidebar
secondaryBackgroundColor = "#ffffff"

# Color del texto general
textColor = "#000000"

# Fuente profesional
font = "sans serif"

[server]
headless = true

[server]
headless = true
